import { ReactNode } from 'react';
import '@/styles/auth.css';
import AuthCarousel from '@/components/auth/AuthFormCarousel';

interface AuthLayoutProps {
  children: ReactNode;
}
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthLayout({ children }: AuthLayoutProps): JSX.Element {
  return (
    <section className='px-5 sm:p-10'>
      {children}

      <div className='right-0 top-0 hidden h-[100vh] w-[50%] pt-5 sm:fixed'>
        <AuthCarousel />
      </div>
    </section>
  );
}
