import { ReactNode } from 'react';
import '@/styles/auth.css';
import AuthCarousel from '@/components/auth/AuthFormCarousel';

interface AuthLayoutProps {
  children: ReactNode;
}
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthLayout({ children }: AuthLayoutProps): JSX.Element {
  return (
    <section className='p-10'>
      {children}

      <div className='fixed right-0 top-3 h-[70vh] w-[50%]'>
        <AuthCarousel />
      </div>
    </section>
  );
}
