// import Navbar from "@/components/Navbar";

import ArrowLeftIcon from '@/assets/icons/ArrowLeftIcon';
import Navbar from '@/components/Navbar';
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <section className='h-screen w-screen overflow-x-hidden overflow-y-hidden bg-cover bg-center px-5 pt-10 sm:bg-[url("/reset-Password-bg.png")] sm:px-20'>
      <div className='hidden sm:block'>
        <Navbar />
      </div>
      <div className='sm:hidden'>
        <Link href={'/auth/signin-signup'} className='flex items-center gap-3'>
          {' '}
          <ArrowLeftIcon />
          <p>Login</p>
        </Link>
      </div>
      <div className='flex h-full w-full justify-center pt-32 sm:pt-32'>
        <div className='w-full sm:w-[450px]'>{children}</div>
      </div>
    </section>
  );
}
