src/
  app/
    page.jsx
  components/
    Navbar.jsx
    Hero.jsx
    CategoryCarousel.jsx
    FeaturedCarousel.jsx
    Locations.jsx
    Sponsored.jsx
    Stats.jsx
    Listings.jsx
    Blog.jsx
    FAQ.jsx
    Footer.jsx
  styles/
    globals.css
public/
  images/
    hero-bg.jpg
    cat-1.jpg
    cat-2.jpg
    cat-3.jpg
    featured-1.jpg
    featured-2.jpg
    featured-3.jpg
    loc-lagos.jpg
    loc-abuja.jpg
    loc-ibadan.jpg
    loc-port.jpg
